# Generated by Django 5.0.6 on 2024-06-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='категория')),
                ('name', models.CharField(max_length=100, verbose_name='название на английском')),
                ('translate', models.CharField(max_length=100, verbose_name='название на русском')),
                ('translate_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='название на кыргызском')),
                ('image', models.ImageField(upload_to='image', verbose_name='изображения')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio', verbose_name='аудио')),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='видео')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='описание, если потребуется')),
            ],
        ),
    ]
